<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c4b19657-ff45-4244-b8ea-f408f4a47a3e</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_30</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[5]/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>