<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>39ff4e2e-be99-498d-be96-9fd791950bdd</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_74</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[8]/div[3]/nav[1]/div[1]/ul[1]/a[9]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Manage your project settings.')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Manage your project settings.</value>
        <webElementGuid>1c3ba246-5b75-4e69-b00e-7607ded938cf</webElementGuid>
    </webElementProperties>
</WebElementEntity>