<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c72eada1-f926-4913-af0e-88a9989162de</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[1]/div[1]/div[2]/header[1]/div[1]/div[1]/div[2]/ul[1]/li[3]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Achini ')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Achini </value>
        <webElementGuid>8b5522a6-0efc-41aa-a5d9-74b91f7aafcf</webElementGuid>
    </webElementProperties>
</WebElementEntity>