<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9a1319eb-7ed1-4cd3-a9b1-c3bfd06bb21e</elementGuidId>
    <imagePath></imagePath>
    <name>li_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[1]/div[1]/div[4]/div[2]/div[3]/div[3]/div[3]/section[1]/div[1]/div[2]/div[1]/div[1]/article[1]/div[1]/div[2]/div[2]/div[1]/ol[1]/li[3]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>