<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fd33aa54-66a7-41f0-9e47-4f37bb413a55</elementGuidId>
    <imagePath></imagePath>
    <name>li_object_39</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[12]/div[1]/div[1]/div[1]/ul[3]/li[20]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>