<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5c71aef7-e16d-47f0-8036-5f2897f0dd9c</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_68</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[8]/div[2]/div[3]/div[1]/div[1]/main[1]/nav[1]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>