<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>fca36891-30af-4304-bc39-f40e686a9012</elementGuidId>
    <imagePath></imagePath>
    <name>li_object_32</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[9]/div[1]/div[1]/div[1]/ul[2]/li[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>