<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>39aa4ad8-44c4-4a48-92df-f746489bc044</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_16</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>