<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>835b295a-b5d0-43d9-8ec7-7d34f06d5490</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_28</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[4]/main[1]/div[2]/div[1]/div[7]/div[1]/div[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>