<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a693e7b2-c596-4a10-847a-f1c2d4defc2e</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_24</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[1]/li[5]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'TestCloud Tunnels')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>TestCloud Tunnels</value>
        <webElementGuid>a9d4aac6-6d35-458e-a0fb-4845613b31ec</webElementGuid>
    </webElementProperties>
</WebElementEntity>