<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1f06a666-a8e1-4ca1-b827-299ee613a586</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_644</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[30]/td[4]/div[2]/div[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Test Suites/Regression/Home/Suites/PolicyCenter/Home Decline - Customer Under 50')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Test Suites/Regression/Home/Suites/PolicyCenter/Home Decline - Customer Under 50</value>
        <webElementGuid>88599cd2-f8a3-48f4-b420-38894137509f</webElementGuid>
    </webElementProperties>
</WebElementEntity>