<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9604d621-1e6d-4446-aea5-7290bc3afaf2</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_285</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[6]/div[2]/div[1]/div[1]/table[1]/tbody[1]/tr[5]/td[2]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Test Suites/Point of Sale/Regression - 3')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Test Suites/Point of Sale/Regression - 3</value>
        <webElementGuid>136394e6-ff52-4322-9baf-05c7e5a523ac</webElementGuid>
    </webElementProperties>
</WebElementEntity>