<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>55810871-f789-4a9c-ac68-dc92e02302e7</elementGuidId>
    <imagePath></imagePath>
    <name>span_object_87</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[9]/td[4]/div[1]/div[1]/div[1]/div[1]/span[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Test Suites/NewActivityOverview-LeftNavigation/ActivityOverview-ListingCalendar-SearchSorting')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Test Suites/NewActivityOverview-LeftNavigation/ActivityOverview-ListingCalendar-SearchSorting</value>
        <webElementGuid>b61ee5d9-87fc-4def-8ac5-bc252875a059</webElementGuid>
    </webElementProperties>
</WebElementEntity>