<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a6024f93-46ab-4a60-a0d9-7f0415674b5c</elementGuidId>
    <imagePath></imagePath>
    <name>p_object_5</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[1]/div[1]/div[4]/div[2]/div[3]/div[3]/div[3]/section[1]/div[1]/div[2]/div[1]/div[17]/article[1]/div[1]/div[2]/div[2]/div[1]/p[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>