<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7f5f693a-094c-4f89-afbd-a94b70639efa</elementGuidId>
    <imagePath></imagePath>
    <name>p_object_3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[1]/div[1]/div[4]/div[2]/div[3]/div[3]/div[3]/section[1]/div[1]/div[2]/div[1]/div[5]/article[1]/div[1]/div[2]/div[2]/div[1]/blockquote[1]/p[6]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>