<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c0e94ca2-3900-41aa-9c93-7fe80bcb5cae</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_24</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[8]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/button[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Next month')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Next month</value>
        <webElementGuid>51a3f8fb-d257-4f4f-8a0c-e1cc7b18f43d</webElementGuid>
    </webElementProperties>
</WebElementEntity>