<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>9dba91cd-bf4a-41a5-8ed4-230a067ffbd6</elementGuidId>
    <imagePath></imagePath>
    <name>span_object_9</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[2]/div[2]/div[1]/div[1]/div[2]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[4]/div[1]/div[1]/div[1]/div[1]/span[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Test Suites/Forr_SPC_Functional/Forr_SPC_Smoke_TopSearchStrings')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Test Suites/Forr_SPC_Functional/Forr_SPC_Smoke_TopSearchStrings</value>
        <webElementGuid>505952f0-45bf-4ef3-9144-8aeb3a08ec52</webElementGuid>
    </webElementProperties>
</WebElementEntity>