<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>26ec29a6-d6a1-4bb7-b077-8a1b51dd7822</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_9</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[1]/div[1]/div[2]/header[1]/div[1]/div[1]/div[2]/ul[1]/li[3]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Glen Rigby')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Glen Rigby</value>
        <webElementGuid>9958a2f6-ca64-4ba2-93e5-5e3f4a8026a9</webElementGuid>
    </webElementProperties>
</WebElementEntity>