<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d3943a99-f707-4c34-a3a2-3c399b7a2af5</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_object_6</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[7]/div[3]/nav[1]/div[1]/ul[1]/a[8]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Update project information and other security configurations.')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Update project information and other security configurations.</value>
        <webElementGuid>2161910b-b8b6-440e-bf08-8303bb80349f</webElementGuid>
    </webElementProperties>
</WebElementEntity>