<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d7705944-a6d9-4853-9535-5e1b224ef354</elementGuidId>
    <imagePath></imagePath>
    <name>div_object_58</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[4]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[4]/div[2]/div[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>