<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>8e83ec80-59c0-4254-8efc-977b1d90d057</elementGuidId>
    <imagePath></imagePath>
    <name>li_object</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/section[1]/div[1]/div[7]/div[1]/div[1]/div[1]/div[4]/form[1]/div[3]/details[1]/div[1]/ul[1]/li[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'[Giveaway] Announcing the new Katalon Community Hub! 🎉')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>[Giveaway] Announcing the new Katalon Community Hub! 🎉</value>
        <webElementGuid>b3dfdefd-8cf9-41c2-8424-edbff19dc964</webElementGuid>
    </webElementProperties>
</WebElementEntity>