<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>6c176cbd-f85d-41e7-9dc7-bb5efd0083cd</elementGuidId>
    <imagePath></imagePath>
    <name>td_object_1</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/div[2]/div[1]/div[3]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[3]/td[6]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'July 15, 2023')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>July 15, 2023</value>
        <webElementGuid>295d9c06-9258-4973-9278-ea0480c692e8</webElementGuid>
    </webElementProperties>
</WebElementEntity>