<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b337834b-c42b-4064-ac41-b2245493a027</elementGuidId>
    <imagePath></imagePath>
    <name>button_object_134</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[8]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[5]/div[3]/button[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>