<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>7a49370b-043b-46a1-ae0c-683ee9cb3790</elementGuidId>
    <imagePath></imagePath>
    <name>span_object_15</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[2]/div[1]/div[3]/div[1]/table[1]/tbody[1]/tr[4]/td[9]/span[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@title,'Test Cases')]</value>
        </entry>
        <entry>
            <key>IMAGE</key>
            <value></value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>title</name>
        <type>Main</type>
        <value>Test Cases</value>
        <webElementGuid>d00d5a7b-24ac-4744-916b-432680d7a02b</webElementGuid>
    </webElementProperties>
</WebElementEntity>